In [ ]:
! pip install transformers datasets torch tensorflow

 # Pipeline
 Pipeline() is the easiest way to pretrained model for inference.

In [11]:
from transformers import pipeline
from datasets import load_dataset, Audio

# Sentimental Analysis
classifier=pipeline('sentiment-analysis')

classifier('We are happy to show you our progress in Data Science')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9998571872711182}]

In [6]:
results=classifier(['We are happy to show you our progress in Data Science',"Hope you don't hate me "])

for result in results:
  print(f"Label :{result['label']}, with score: {round(result['score'],4)}")

Label :POSITIVE, with score: 0.9999
Label :POSITIVE, with score: 0.992


In [7]:
# Named Enitity Recognition
classifier=pipeline('ner')
classifier('My Name is Om, Im prepareing for Data Scientiest role')

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

Device set to use cpu


[{'entity': 'I-PER',
  'score': np.float32(0.98746115),
  'index': 4,
  'word': 'O',
  'start': 11,
  'end': 12},
 {'entity': 'I-PER',
  'score': np.float32(0.9826067),
  'index': 5,
  'word': '##m',
  'start': 12,
  'end': 13},
 {'entity': 'I-MISC',
  'score': np.float32(0.30425444),
  'index': 12,
  'word': 'Data',
  'start': 33,
  'end': 37},
 {'entity': 'I-PER',
  'score': np.float32(0.38512334),
  'index': 13,
  'word': 'Sc',
  'start': 38,
  'end': 40},
 {'entity': 'I-MISC',
  'score': np.float32(0.54017717),
  'index': 15,
  'word': '##iest',
  'start': 44,
  'end': 48}]

In [8]:
# Question Answering
classifier=pipeline('question-answering')
classifier(question='What is HuggingFace',context="Hugging Face is a company that provides open-source NLP technologies.")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Device set to use cpu


{'score': 0.6195597648620605,
 'start': 16,
 'end': 68,
 'answer': 'a company that provides open-source NLP technologies'}

In [10]:
# Text Generation
classifier=pipeline('text-generation',model='gpt2')
classifier('Once up on a time in mumbai')

Device set to use cpu
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'Once up on a time in mumbai, they don\'t have a real shop, they do all their business indoors," says Shruti Japayal, CEO of Anapal.\n\n"When you shop online you have no way'}]

In [15]:
# Automic speech recognition
classifier=pipeline('automatic-speech-recognition',model='facebook/wav2vec2-base-960h')
# Load Audio data
dataset=load_dataset('PolyAI/minds14',name='en-US',split='train')

dataset=dataset.cast_column('audio',Audio(sampling_rate=classifier.feature_extractor.sampling_rate))

result=classifier(dataset[:4]['audio'])

for d in result:
  print(d['text'])

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device set to use cpu


I WOULD LIKE TO SET UP A JOINT ACCOUNT WITH MY PARTNER HOW DO I PROCEED WITH DOING THAT
FONDERING HOW I'D SET UP A JOIN TO HELL T WITH MY WIFE AND WHERE THE AP MIGHT BE
I I'D LIKE TOY SET UP A JOINT ACCOUNT WITH MY PARTNER I'M NOT SEEING THE OPTION TO DO IT ON THE APSO I CALLED IN TO GET SOME HELP CAN I JUST DO IT OVER THE PHONE WITH YOU AND GIVE YOU THE INFORMATION OR SHOULD I DO IT IN THE AP AN I'M MISSING SOMETHING UQUETTE HAD PREFERRED TO JUST DO IT OVER THE PHONE OF POSSIBLE THINGS
HOW DO I FURN A JOINA COUT


In [17]:
# Using another model and tokenizer in the pipeline
from transformers import AutoModelForSequenceClassification,AutoTokenizer
# AutoTokenizer- It selectes automatic tokenizer for appropriate model
# AutoModelForSequenceClassification- Automatically picks the right model architecture for the seqence to sequence classification tasks


model='bert-base-uncased'

tokenizer=AutoTokenizer.from_pretrained(model)

text=['Hello Beautiful, Hope you are doing well']

tokens=tokenizer(text,padding=True,truncation=True,return_tensors='pt')
print(tokens)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

{'input_ids': tensor([[ 101, 7592, 3376, 1010, 3246, 2017, 2024, 2725, 2092,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [20]:
# Example
text='Attention is all you need'

tokens=tokenizer.tokenize(text)
print('Tokens:',tokens)
input_id=tokenizer.convert_tokens_to_ids(tokens)
print('input_id:',input_id)

Tokens: ['attention', 'is', 'all', 'you', 'need']
input_id: [20726, 10127, 10367, 10855, 15415]


In [28]:
model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
tokenizer = AutoTokenizer.from_pretrained(model_name)


encoding = tokenizer("We are very happy to show you the 🤗 Transformers library.")
print(encoding)

{'input_ids': [101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103, 100, 58263, 13299, 119, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [31]:
tokenizer(
    ["We are very happy to show you the 🤗 Transformers library.", "We hope you don't hate it."],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="pt",
)


{'input_ids': tensor([[  101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103,   100,
         58263, 13299,   119,   102],
        [  101, 11312, 18763, 10855, 11530,   112,   162, 39487, 10197,   119,
           102,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])}

In [32]:
tokenizer(
    ["We are very happy to show you the 🤗 Transformers library.", "We hope you don't hate it."],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="tf",
)

{'input_ids': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[  101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103,
          100, 58263, 13299,   119,   102],
       [  101, 11312, 18763, 10855, 11530,   112,   162, 39487, 10197,
          119,   102,     0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]], dtype=int32)>}

#Model Specific Tokenizer

In [21]:
from transformers import BertTokenizer

tokenizer=BertTokenizer.from_pretrained('bert-base-uncased')

tokenizer('Hello Beautiful, Hope you are doing well',padding=True,truncation=True,return_tensors='pt')

{'input_ids': tensor([[ 101, 7592, 3376, 1010, 3246, 2017, 2024, 2725, 2092,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [24]:
from transformers import GPT2Tokenizer

tokenizer=GPT2Tokenizer.from_pretrained('gpt2')
tokenizer('Hello Beautiful, Hope you are doing well',truncation=True,return_tensors='pt')

{'input_ids': tensor([[15496, 23762,    11, 13408,   345,   389,  1804,   880]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [26]:
from transformers import RobertaTokenizer

tokenizer=RobertaTokenizer.from_pretrained('roberta-base')
tokenizer('Hello Beautiful, Hope you are doing well',truncation=True,padding=True, return_tensors='pt')

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

{'input_ids': tensor([[    0, 31414, 20081,     6,  8012,    47,    32,   608,   157,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

# Autoclass
 Automatically selects appropriate architecture for appropriate pretrained model

In [18]:
model_name='nlptown/bert-base-multilingual-uncased-sentiment'

model=AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer=AutoTokenizer.from_pretrained(model_name)


classifier=pipeline('sentiment-analysis',model=model ,tokenizer=tokenizer)
classifier('Nous sommes très heureux de vous présenter la bibliothèque 🤗 Transformers.')

Device set to use cpu


[{'label': '5 stars', 'score': 0.7272651195526123}]

In [33]:
from transformers import AutoModel,AutoTokenizer

model='bert-base-uncased'

tokenizer=AutoTokenizer.from_pretrained(model)

input=tokenizer('Hello! how are you ?',return_tensors='pt')

model=AutoModel.from_pretrained(model)

output=model(**input)
print(output)

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.0253,  0.1231, -0.2382,  ..., -0.3488,  0.1398,  0.4258],
         [-0.1453, -0.3217,  0.0043,  ..., -0.1615,  0.8794, -0.1689],
         [-0.5834, -0.1398,  0.1819,  ..., -0.1027,  0.4442,  0.2527],
         ...,
         [-0.3482, -0.9069,  0.6542,  ..., -0.4323,  0.3802, -0.7148],
         [-0.5838, -0.8746, -0.7932,  ...,  0.1795, -0.1009, -0.0455],
         [ 0.5331, -0.1100, -0.2428,  ...,  0.3198, -0.4347, -0.2256]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.9471, -0.4129, -0.8782,  0.8561,  0.6028, -0.1768,  0.9398,  0.2781,
         -0.7869, -1.0000, -0.4512,  0.9509,  0.9835,  0.5835,  0.9700, -0.8700,
         -0.6356, -0.6893,  0.3251, -0.7326,  0.7685,  1.0000,  0.1184,  0.3327,
          0.5244,  0.9932, -0.8821,  0.9630,  0.9766,  0.7422, -0.8089,  0.1155,
         -0.9910, -0.2254, -0.9018, -0.9934,  0.3980, -0.8234, -0.0662,  0.0478,
         -0.9294,  0.2793,  1.00

In [34]:
output.last_hidden_state.shape

torch.Size([1, 8, 768])

In [35]:
from transformers import TFAutoModelForSequenceClassification

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
tf_model = TFAutoModelForSequenceClassification.from_pretrained(model_name)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [37]:
a=tokenizer(
    ["We are very happy to show you the Transformers library.", "We hope you don't hate it."],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="tf",
)

tf_model(a)

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[ 0.47289827,  0.5576924 ,  0.559643  , -0.38325956, -0.982609  ],
       [ 0.5445985 ,  0.7913339 ,  0.78838   , -0.35477197, -1.4122335 ]],
      dtype=float32)>, hidden_states=None, attentions=None)

# Save a Model

In [39]:
pt_save_directory = "./pt_save_pretrained"
tokenizer.save_pretrained(pt_save_directory)
model.save_pretrained(pt_save_directory)

In [40]:
# You can use the saved model for inference
model=AutoModelForSequenceClassification.from_pretrained("./pt_save_pretrained")


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at ./pt_save_pretrained and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


# Custom Model builds
  In which you can change the configuration of the model.

In [46]:
from transformers import AutoConfig

my_config=AutoConfig.from_pretrained('bert-base-uncased',n_heads=12)
model=AutoModel.from_config(my_config)

# Custom Classification model using AutoModel

In [52]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel

# Define a custom classification model
class CustomClassificationModel(nn.Module):
    def __init__(self, model_checkpoint, num_labels):
        super(CustomClassificationModel, self).__init__()
        self.automodel = AutoModel.from_pretrained(model_checkpoint)
        self.classifier = nn.Linear(self.automodel.config.hidden_size, num_labels)

    def forward(self, input_ids, attention_mask=None, token_type_ids=None):
        outputs = self.automodel(input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)
        # Get the hidden state of the [CLS] token
        cls_output = outputs.last_hidden_state[:, 0, :]
        logits = self.classifier(cls_output)
        return logits

# Model checkpoint and number of labels
model_checkpoint = 'bert-base-uncased'
num_labels = 2  # Example for binary classification

# Initialize the tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

# Tokenize a sample text
inputs = tokenizer("Hello, this is an example using a custom classification head.", return_tensors='pt')

# Initialize the custom model
model = CustomClassificationModel(model_checkpoint, num_labels)

# Perform a forward pass
logits = model(**inputs)

# Apply softmax to get probabilities
probabilities = F.softmax(logits, dim=-1)

# Convert probabilities to predicted class labels
predictions = torch.argmax(probabilities, dim=-1)

# Print the probabilities and the predicted class
print(probabilities)
print(predictions)

tensor([[0.5538, 0.4462]], grad_fn=<SoftmaxBackward0>)
tensor([0])


# AutoModel for **classes
Automatica selects appropriate model architecture with task specific head for various NLP task

In [54]:
from transformers import AutoModelForSequenceClassification,AutoTokenizer
import torch.nn.functional as F
import torch

model='bert-base-uncased'
tokenizer=AutoTokenizer.from_pretrained(model)
model= AutoModelForSequenceClassification.from_pretrained(model)

inputs=tokenizer('Hello! how you doing ?',return_tensors='pt')

# Perform forward pass
outputs=model(**inputs)
logits=outputs.logits

# Apply probabilites
probabilities=F.softmax(logits,dim=-1)
predictions=torch.argmax(probabilities,dim=-1)

print(probabilities)
print(predictions)



Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tensor([[0.4431, 0.5569]], grad_fn=<SoftmaxBackward0>)
tensor([1])


In [57]:
## AutoModelForCasualLM - Automatically loads a model that is good for casual language modeling

from transformers import AutoModelForCausalLM, AutoTokenizer
# Initialize the tokenizer and model
model='gpt2'
tokenizer=AutoTokenizer.from_pretrained(model)
model=AutoModelForCausalLM.from_pretrained(model)

# Tokenize input
inputs=tokenizer('India is going to win ',return_tensors='pt')

# Generate text
outputs=model.generate(inputs['input_ids'],max_length=50,num_return_sequences=1)

# Decode and print the generated text
generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(generated_text)



The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


India is going to win  the war on drugs.  The war on drugs is going to be a war on the poor.  The war on drugs is going to be a war on the poor.  The war on drugs


In [60]:
# AutoModelForTokenClassifcation- For specific token level tasks
from transformers import AutoTokenizer,AutoModelForTokenClassification

# Initialize tokenizer and model
model='dbmdz/bert-large-cased-finetuned-conll03-english'
tokenizer=AutoTokenizer.from_pretrained(model)
model=AutoModelForTokenClassification.from_pretrained(model)

# Tokenize input text
inputs=tokenizer('Virat will win the match',return_tensors='pt')

# Preform forward pass
outputs=model(**inputs)
logits=outputs.logits

# Get predictions
predictions=torch.argmax(logits,dim=-1)

# Print the prediction
predicted_tokens = [model.config.id2label[prediction.item()] for prediction in predictions[0]]
print(predicted_tokens)

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


['O', 'I-ORG', 'I-ORG', 'I-ORG', 'O', 'O', 'O', 'O', 'O']


# Model Specific class-
  The model-specific-class is designed to perform specific NLP task,By adding appropriate heads to the pretrianed model.

In [62]:
from transformers import BertTokenizer, BertForSequenceClassification
import torch

# Load the tokenizer and model
model_checkpoint = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(model_checkpoint)
model = BertForSequenceClassification.from_pretrained(model_checkpoint)

# Define labels (these are examples; adjust based on your actual model's training)
labels = ["Negative", "Positive"]

# Input sentences
sentences = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this"
]

# Tokenize and encode the sentences
inputs = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')

# Perform a forward pass and get logits
outputs = model(**inputs).logits

# Apply softmax to get probabilities
probabilities = torch.nn.functional.softmax(outputs, dim=-1)

# Get the predicted class
predictions = torch.argmax(probabilities, dim=-1)

# Print the probabilities and predicted classes
for i, sentence in enumerate(sentences):
    print(f"Sentence: {sentence}")
    print(f"Probabilities: {probabilities[i].tolist()}")
    print(f"Predicted Class: {labels[predictions[i]]}")


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Sentence: I've been waiting for a HuggingFace course my whole life.
Probabilities: [0.4621756374835968, 0.537824273109436]
Predicted Class: Positive
Sentence: I hate this
Probabilities: [0.4442093074321747, 0.5557907223701477]
Predicted Class: Positive


In [63]:
# GPT2LMHead Model
from transformers import GPT2TokenizerFast,GPT2LMHeadModel

# Load model and tokenizer
model='gpt2'
tokenizer=GPT2Tokenizer.from_pretrained(model)
model=GPT2LMHeadModel.from_pretrained(model)

# Input prompt
prompt='Once upon time'

# Tokenize and encode the prompt
inputs=tokenizer(prompt,return_tensors='pt')

# Generate Text
outputs=model.generate(inputs['input_ids'],max_length=50,num_return_sequences=1)

# Decode and print generated text
generated_text=tokenizer.decode(outputs[0],skip_special_tokens=True)
print('Generated Text',generated_text)


The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Generated Text Once upon time, the two men were able to get a hold of each other and began to talk.

"I'm sorry, I'm sorry," he said. "I'm sorry. I'm sorry. I'm sorry. I'm


# AutoConfig class-
  AutoConfig class automatically loads the configuration of pre-trained model.This configuration includes the architecture and hyperparameters of the model.

In [65]:
from transformers import AutoConfig

# Load model
model='bert-base-uncased'
model_config=AutoConfig.from_pretrained(model)
print(model_config)

BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.51.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



In [67]:
# Modify configuration
model_config.num_labels=5 # Change the number of labels for classification

# print modified configuration
print(model_config)
model_config.hidden_act

BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.51.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



'gelu'

In [68]:
# Using configuration to initialize the model
from transformers import AutoConfig,AutoModelForSequenceClassification

# Load the model
model='bert-base-uncased'
model_config=AutoConfig.from_pretrained(model)
model_config.num_labels=5 # Change the number of labels for classification

# Initialize the model with modified configuration
model=AutoModelForSequenceClassification.from_config(model_config)

# Print model
print(model)


BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

# Model specific configuration classes-
Used to define architecture and hyperparameter of specific model.

In [71]:
# BERT Configuration
from transformers import BertConfig,BertForSequenceClassification

# Initialize model and modify the model
model_config=BertConfig.from_pretrained('bert-base-uncased')
model_config.num_labels=5 # Change number of labels for classification

# Initialize the model with updated configuration
model=BertForSequenceClassification(model_config)
print(model)


BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [73]:
# GPT-2 configuration
from transformers import GPT2Config,GPT2LMHeadModel

# Initialize model and modify it
model_config=GPT2Config.from_pretrained('gpt2')
model_config.output_hidden_state=True # change the configuration to output hidden state

# intialize the GPT-2 model with modified configureation
model=GPT2LMHeadModel(model_config)

# Print it
print(model)

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)


In [74]:
# DistilBert Configuration
from transformers import  DistilBertConfig,DistilBertForTokenClassification

# initialize the model and modify it
model_config=DistilBertConfig.from_pretrained('distilbert-base-uncased')
model_config.num_labels=10 # Change number of labels for NER

# Inifialize the modified model
model=DistilBertForTokenClassification(model_config)
print(model)

DistilBertForTokenClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
   

# Dataset Classs-
* It is use to handle and manipulate the data effeciently.
* It coverse the various operations like loading,transforming,processing the data

In [75]:
from datasets import load_dataset

# Load dataset from Hugging face hub
dataset=load_dataset('imdb')

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

unsupervised-00000-of-00001.parquet:   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [76]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [77]:
dataset['train'][0]

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far be

In [78]:
train_subset=dataset['train'].select(range(10000))

In [79]:
train_subset

Dataset({
    features: ['text', 'label'],
    num_rows: 10000
})

In [80]:
dataset['train'].features

{'text': Value(dtype='string', id=None),
 'label': ClassLabel(names=['neg', 'pos'], id=None)}

In [81]:
# Split the dataset into train and test sets
split_dataset=dataset['train'].train_test_split(test_size=0.1)
train_data=split_dataset['train']
test_data=split_dataset['test']

In [84]:
# map() - appllies a function to all examples in the dataset.

# Define a preprocessing function
def preprocess_function(examples):
    return tokenizer(examples['text'], truncation=True)

# Apply the preprocessing function to the dataset
tokenized_dataset = dataset['train'].map(preprocess_function, batched=True)


Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

# DataLodaer -
Used to create batched of data for training and evaluation

In [85]:
from torch.utils.data import DataLoader

# Create dataloader for training data
train_dataloader=DataLoader(tokenized_dataset,batch_size=8,shuffle=True)


In [ ]:
# Print the first batch
for batch in train_dataloader:
  print(batch)


# Load_dataset-
Used to load file from locally or directly from internet

In [88]:
from datasets import load_dataset

# Specify the URL of the dataset (assuming a CSV file format)
url = 'https://people.sc.fsu.edu/~jburkardt/data/csv/airtravel.csv'

dataset=load_dataset('csv',data_files=url)

print(dataset['train'][0])

Generating train split: 0 examples [00:00, ? examples/s]

{'Month': 'JAN', ' "1958"': 340, ' "1959"': 360, ' "1960"': 417}


# DataCollector-
Used to collect data into batches and prepare them for model input

In [90]:
from transformers import DataCollatorWithPadding,AutoTokenizer
from torch.utils.data import DataLoader

# Initialize the tokenizer
tokenizer=AutoTokenizer.from_pretrained('bert-base-uncased')

# Define a simple dataset
dataset = [
    {"text": "I've been waiting for a HuggingFace course my whole life."},
    {"text": "I hate this"}
]

# Tokenize the dataset
tokenized_dataset=[tokenizer(data['text'],truncation=True)for data in dataset]

# Initialize the DataCollector
data_collector=DataCollatorWithPadding(tokenizer=tokenizer)

# Create a Dataloader
dataloader=DataLoader(tokenized_dataset,batch_size=2,collate_fn=data_collector)

# Print batch
for batch in dataloader:
  print(batch)

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [94]:
from transformers import DataCollatorForLanguageModeling,AutoTokenizer
from torch.utils.data import DataLoader

# Initialize the tokenizer
tokenizer=AutoTokenizer.from_pretrained('bert-base-uncased')

# Define a simple dataset
dataset = [
    {"text": "I've been waiting for a HuggingFace course my whole life."},
    {"text": "I hate this"}
]

# Tokenize the dataset
tokenized_dataset = [tokenizer(data['text'], truncation=True) for data in dataset]

# Initialize the datacollator with masking
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=True, mlm_probability=0.15)

# Create dataloader
dataloader=DataLoader(tokenized_dataset,batch_size=2,collate_fn=data_collector)

for batch in dataloader:
  print(batch)


{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [96]:
# DataCollatorForSeq2Seq
# Prepare data for sequence to sequence task such as translation and summarization

from transformers import DataCollatorForSeq2Seq,AutoTokenizer,AutoModelForSeq2SeqLM
from torch.utils.data import DataLoader

# initialize the model and Tonekizer
tokenizer=AutoTokenizer.from_pretrained('t5-small')
model=AutoModelForSeq2SeqLM.from_pretrained('t5-small')

# Define a simple dataset
dataset = [
    {"text": "translate English to French: HuggingFace is a great library."},
    {"text": "translate English to French: I love programming."}
]

# Tokenize the dataset
tokenized_dataset=[tokenizer(data['text'],truncation=True)for data in dataset]

# Initialize the datacollator
data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer,model=model)

# Create dataloader
data_loader=DataLoader(tokenized_dataset,batch_size=2,collate_fn=data_collator)

# Print
for data in data_loader:
  print(data)

{'input_ids': tensor([[13959,  1566,    12,  2379,    10, 11560,  3896,   371,  3302,    19,
             3,     9,   248,  3595,     5,     1],
        [13959,  1566,    12,  2379,    10,    27,   333,  6020,     5,     1,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]]), 'labels': None}


# TrainingArguments-
Used to specify various configuration and hyperparameter for the training process.

In [ ]:
# Ex-
from transformers import TrainingArguments

# Define the training arguments
training_args = TrainingArguments(
    output_dir='./results',          # Directory to save the model checkpoints
    evaluation_strategy='epoch',     # Evaluate at the end of every epoch
    learning_rate=2e-5,              # Learning rate for the optimizer
    per_device_train_batch_size=8,   # Batch size for training
    per_device_eval_batch_size=8,    # Batch size for evaluation
    num_train_epochs=3,              # Number of training epochs
    weight_decay=0.01,               # Weight decay for the optimizer
    logging_dir='./logs',            # Directory to save the logs
    logging_steps=10,                # Log training metrics every 10 steps
    save_steps=500,                  # Save model checkpoint every 500 steps
    save_total_limit=2,              # Limit the total number of checkpoints
)

# Trainer API-
* Simplifies the process of training and evaluating models.
* Provides a flexible and extensible framework for various training and evaluation tasks.

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset
import numpy as np
from sklearn.metrics import accuracy_score

# Load the dataset
dataset = load_dataset('imdb')

# Load the tokenizer and model
model_checkpoint = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint)

# Tokenize the dataset
def tokenize_function(examples):
    return tokenizer(examples['text'], padding='max_length', truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Define the training arguments
training_args = TrainingArguments(
    output_dir='./results',
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir='./logs',
)

# Define a compute metrics function
def compute_metrics(p):
    preds = np.argmax(p.predictions, axis=1)
    return {"accuracy": accuracy_score(p.label_ids, preds)}

# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['test'],
    compute_metrics=compute_metrics
)

# Train the model
trainer.train()

# Evaluate the model
eval_results = trainer.evaluate()

# Print evaluation results
print(f"Evaluation results: {eval_results}")

# Save the model
trainer.save_model()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.


<IPython.core.display.Javascript object>

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:

 ··········


wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: ombhandwalkar38126 (ombhandwalkar38126-student) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


In [ ]:

from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset
from datasets import load_metric
import numpy as np
from sklearn.metrics import accuracy_score

# Load the dataset
dataset = load_dataset('imdb')

# Load the tokenizer and model
model_checkpoint = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint)

# Tokenize the dataset
def tokenize_function(examples):
    return tokenizer(examples['text'], padding='max_length', truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Load the accuracy metric
metric = load_metric('accuracy')

# Define the training arguments
training_args = TrainingArguments(
    output_dir='./results',
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir='./logs',
)

# Define a compute metrics function
def compute_metrics(p):
    preds = np.argmax(p.predictions, axis=1)
    metric_result = metric.compute(predictions=preds, references=p.label_ids)
    return metric_result

# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['test'],
    compute_metrics=compute_metrics
)

# Train the model
trainer.train()

# Evaluate the model
eval_results = trainer.evaluate()

# Print evaluation results
print(f"Evaluation results: {eval_results}")

# Save the model
trainer.save_model()